### ISSUE TITLE
www.conf deleted/recreated with each chef run

### ISSUE THREAD

**Issue by kkeane** [yevgenko/cookbook-php-fpm#64]
This is for version 0.7.0.

The recipe php_fpm::configure uses a resource (actually, a definition) php_fpm_pool www that will unconditionally disable the www pool (and thus delete the www.conf file) even if the www pool is actually needed, and will be re-created in the next step.

This is a problem because, first, it makes this cookbook non-idempotent. Secondly, some tools (such as a nagios plugin) counts the number of updated resources, and produce a warning when too man  resources are updated.

The easiest way to see this happening is in the default case: simply add php-fpm::default to your runlist.

**Comment by dwradcliffe** [comment]
Yep, this is a problem for me too. Why does it disable and then re-enable by default?

**Comment by dwradcliffe** [comment]
There's a fix in PR #62

**Comment by yevgenko** [comment]
> Why does it disable and then re-enable by default?

This is because at some point I decided to make sure that no others pools exists upon install of package, i.e. to remove the default pools introduced during package installation, which is on most systems was named 'www', suddenly in default attributes we had the pool with the same name for the demo purposes.

I'm now considering if we should touch default pools available on the system at all, since the user can disable those by passing corresponding attributes to the node.
